# Generated by Django 6.1 on 2026-08-24 05:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0002_skillgap'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='Beginner', max_length=50)),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('course', 'Course'), ('project', 'Project'), ('documentation', 'Documentation')], default='course', max_length=50)),
                ('content_url', models.URLField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Estimated completion time in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_resources', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Learning Resource',
                'verbose_name_plural': 'Learning Resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('recommended_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_recommendations', to='skills.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='students.studentprofile')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_recommendations', to='courses.learningresource')),
            ],
            options={
                'verbose_name': 'Learning Recommendation',
                'verbose_name_plural': 'Learning Recommendations',
                'ordering': ['-priority', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'resource'), name='unique_student_resource_recommendation')],
            },
        ),
    ]
