# Generated by Django 6.1 on 2026-08-24 06:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_opportunity_opportunityskillrequirement'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.FloatField(default=0.0)),
                ('skill_match_score', models.FloatField(default=0.0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='companies.opportunity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_matches', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Opportunity Match',
                'verbose_name_plural': 'Opportunity Matches',
                'ordering': ['-match_score'],
                'constraints': [models.UniqueConstraint(fields=('student', 'opportunity'), name='unique_student_opportunity_match')],
            },
        ),
    ]
