// Barrel export for API layer
export { default as apiClient } from './axios'
export { default as ENDPOINTS } from './endpoints'
export { authApi } from './auth.api'
export { profileApi } from './profile.api'
export { skillApi } from './skill.api'
export { assessmentApi } from './assessment.api'
export { courseApi } from './course.api'
export { opportunityApi } from './opportunity.api'
export { applicationApi } from './application.api'
export { analyticsApi } from './analytics.api'
