import apiClient from './axios'
import ENDPOINTS from './endpoints'

export const courseApi = {
  // List active learning resources (supports params: { skill, type, level, search })
  getResources: async (params = {}) => {
    const { data } = await apiClient.get(ENDPOINTS.COURSES.RESOURCES, { params })
    return data
  },

  // Get student's personalized recommendations generated by Phase 9 Recommendation Engine
  getRecommendations: async () => {
    const { data } = await apiClient.get(ENDPOINTS.COURSES.RECOMMENDATIONS)
    return data
  },

  // Update recommendation status (pending, in_progress, completed)
  updateRecommendationStatus: async (id, status) => {
    const { data } = await apiClient.patch(ENDPOINTS.COURSES.RECOMMENDATION_DETAIL(id), { status })
    return data
  },
}

export default courseApi
