# Generated by Django 6.1 on 2026-08-24 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='guest_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['guest_id', '-updated_at'], name='ai_aiconver_guest_i_0668f6_idx'),
        ),
    ]
