# Generated by Django 6.1 on 2026-08-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aiconversation_guest_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
