# Generated by Django 6.1 on 2026-08-25 19:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_aimessage_suggestions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=20)),
                ('file_size', models.IntegerField(default=0)),
                ('extracted_text', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('resume', 'Resume/CV'), ('course_material', 'Course Material'), ('job_description', 'Job Description'), ('interview_prep', 'Interview Preparation'), ('technical', 'Technical Document'), ('general', 'General Document'), ('unknown', 'Unknown')], default='general', max_length=50)),
                ('analysis_result', models.JSONField(blank=True, default=dict)),
                ('ai_provider', models.CharField(default='ollama', max_length=50)),
                ('ocr_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIDocumentChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='ai.aidocument')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aidocument',
            index=models.Index(fields=['user', '-created_at'], name='ai_aidocume_user_id_47472f_idx'),
        ),
        migrations.AddIndex(
            model_name='aidocument',
            index=models.Index(fields=['guest_id', '-created_at'], name='ai_aidocume_guest_i_43f344_idx'),
        ),
        migrations.AddIndex(
            model_name='aidocumentchatmessage',
            index=models.Index(fields=['document', 'created_at'], name='ai_aidocume_documen_d93ffb_idx'),
        ),
    ]
