# Generated by Django 6.1 on 2026-08-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_aidocument_aidocumentchatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='attachment',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
