# Generated by Django 6.1 on 2026-08-24 05:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillGap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_score', models.PositiveIntegerField(default=0)),
                ('required_score', models.PositiveIntegerField(default=0)),
                ('gap_score', models.PositiveIntegerField(default=0)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('improving', 'Improving'), ('resolved', 'Resolved')], default='open', max_length=50)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('career_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='skills.careerrole')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='skills.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Skill Gap',
                'verbose_name_plural': 'Skill Gaps',
                'ordering': ['-gap_score'],
                'constraints': [models.UniqueConstraint(fields=('student', 'skill', 'career_role'), name='unique_student_skill_gap')],
            },
        ),
    ]
