# Generated by CareerSync for course-completion skill sync.
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('skills', '0002_skillgap')]

    operations = [
        migrations.AlterField(
            model_name='studentskill',
            name='source',
            field=models.CharField(
                choices=[
                    ('manual', 'Manual Entry'),
                    ('resume', 'Resume Parsing'),
                    ('assessment', 'Skill Assessment'),
                    ('practice', 'AI Practice'),
                    ('course', 'Course Completion'),
                ],
                default='manual',
                max_length=50,
            ),
        ),
    ]
