# Generated by Django 6.1 on 2026-08-24 06:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('skills', '0002_skillgap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('opportunity_type', models.CharField(choices=[('internship', 'Internship'), ('job', 'Job')], default='internship', max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(default='Remote', max_length=150)),
                ('work_mode', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'Onsite')], default='remote', max_length=50)),
                ('duration', models.CharField(default='6 months', max_length=100)),
                ('stipend_salary', models.CharField(blank=True, default='₹25k/mo', max_length=100)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='published', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='companies.company')),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpportunitySkillRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minimum_score', models.PositiveIntegerField(default=70)),
                ('weight', models.FloatField(default=1.0)),
                ('is_required', models.BooleanField(default=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='companies.opportunity')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_requirements', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Opportunity Skill Requirement',
                'verbose_name_plural': 'Opportunity Skill Requirements',
                'constraints': [models.UniqueConstraint(fields=('opportunity', 'skill'), name='unique_opportunity_skill')],
            },
        ),
    ]
