# Generated by Django 6.1 on 2026-08-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_application_applicationstatushistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
