# Generated by Django 6.1 on 2026-08-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='institution_type',
        ),
    ]
