# Generated by Django 6.1 on 2026-08-25 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('institutions', '0002_remove_institution_institution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='enrolled_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_resources', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='instructor_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='rating',
            field=models.FloatField(default=4.8),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='thumbnail_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
