# Generated by Django 6.1 on 2026-08-25 20:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_learningresource_enrolled_count_and_more'),
        ('students', '0002_studentprofile_career_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('completed_lessons', models.JSONField(blank=True, default=list)),
                ('last_played_lesson_id', models.CharField(blank=True, max_length=100)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Course Enrollment',
                'verbose_name_plural': 'Course Enrollments',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='CoursePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(default='UPI', max_length=50)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course Payment',
                'verbose_name_plural': 'Course Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='learningrecommendation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Learning Recommendation', 'verbose_name_plural': 'Learning Recommendations'},
        ),
        migrations.RemoveConstraint(
            model_name='learningrecommendation',
            name='unique_student_resource_recommendation',
        ),
        migrations.RenameField(
            model_name='learningrecommendation',
            old_name='recommended_reason',
            new_name='reason',
        ),
        migrations.AddField(
            model_name='learningrecommendation',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='certificate_included',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='curriculum',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='faqs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='what_you_will_learn',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.learningresource'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='coursepayment',
            name='enrollment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_record', to='courses.courseenrollment'),
        ),
        migrations.AddField(
            model_name='coursepayment',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='courses.learningresource'),
        ),
        migrations.AddField(
            model_name='coursepayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_payments', to='students.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('student', 'resource')},
        ),
    ]
