# Generated by Django 6.1 on 2026-08-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='career_goal',
            field=models.CharField(blank=True, default='Full Stack Developer', max_length=150),
        ),
    ]
