# Generated by Django 6.1 on 2026-08-24 04:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=150, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Career Role',
                'verbose_name_plural': 'Career Roles',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Database', 'Database'), ('DevOps', 'DevOps'), ('Cloud', 'Cloud'), ('AI/ML', 'AI/ML'), ('Cybersecurity', 'Cybersecurity'), ('Soft Skill', 'Soft Skill'), ('Other', 'Other')], db_index=True, default='Programming', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkillScoreHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField()),
                ('source', models.CharField(default='manual', max_length=50)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to='skills.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Skill Score History',
                'verbose_name_plural': 'Skill Score Histories',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='CareerSkillRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_score', models.PositiveIntegerField(default=70)),
                ('weight', models.FloatField(default=1.0)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('career_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='skills.careerrole')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_requirements', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Career Skill Requirement',
                'verbose_name_plural': 'Career Skill Requirements',
                'ordering': ['-required_score'],
                'constraints': [models.UniqueConstraint(fields=('career_role', 'skill'), name='unique_career_role_skill')],
            },
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField(default=0)),
                ('level', models.CharField(default='Beginner', max_length=50)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('resume', 'Resume Parsing'), ('assessment', 'Skill Assessment'), ('practice', 'AI Practice')], default='manual', max_length=50)),
                ('last_assessed_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_skills', to='skills.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Skill',
                'verbose_name_plural': 'Student Skills',
                'ordering': ['-score'],
                'constraints': [models.UniqueConstraint(fields=('student', 'skill'), name='unique_student_skill')],
            },
        ),
    ]
